### ISSUE TITLE
how to use this package

### ISSUE THREAD

**Issue by sloth2012** [seratch/java-time-backport#1]
I build a sbt project，import this package， and build it with jdk7。but found that it still report error like this: “ Prohibited package name: java.time” .  
I'd like to know how you use this in low level jdk project.
3ku!

**Comment by seratch** [comment]
I've never seen the error in my projects. If you share me a minimum working example, I may be able to help you.

**Comment by Mart-Bogdan** [comment]
@seratch would be cool if it would be published in maven central

**Comment by Mart-Bogdan** [comment]
my bad, it's in maven aleady, just badge, no snippet in README :-)

**Comment by le-jhe** [comment]
Actually, I am able to reproduce the error with this main class
```java
import java.time.LocalTime;

public class JavaTimeBackportTester {

	public static void main(String[] args) {
		System.out.println("XXXXXXXX java.version="+System.getProperty("java.specification.version"));
		new JavaTimeBackportTester().tester();

	}

	public void tester() {
		LocalTime someTime = LocalTime.now();
		System.out.println("I expect this won't compile as java.time package is reserved");
		// actually : Exception in thread "main" java.lang.SecurityException: java.time.LocalTime - protected system package 'java.time'
	}

}
```

just a basic pom to import com.github.seratch:java-time-backport:1.0.0 and force java version to 1.7 (I can provide it if needed).

The result is the following exception:
```
XXXXXXXX java.version=1.7
Exception in thread "main" java.lang.SecurityException: java.time.LocalTime - protected system package 'java.time'
	at java.lang.ClassLoader.checkClassName(ClassLoader.java:270)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:312)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:155)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:712)
	at java.net.URLClassLoader.access$400(URLClassLoader.java:93)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1164)
	at java.security.AccessController.doPrivileged(AccessController.java:456)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:595)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:777)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:750)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:731)
	at JavaTimeBackportTester.tester(JavaTimeBackportTester.java:20)
	at JavaTimeBackportTester.main(JavaTimeBackportTester.java:15)
```

java prohibits a certain number of packages to be used for you own class, as probably "java.time".

Problem is the same even with `-Xbootclasspath/p:c:\path\to\java-time-backport-1.0.0.jar` [on windows]

Am I missing something ?

**Comment by le-jhe** [comment]
After some tries, I have been able to use it. With the following hints:
* This module is probably compiled as java6
  * so, use java6 or java7 for your code
  * does not work for java5 or below
* to bypass the `protected system package 'java.time'` error, you need to put this library in your boot classpath
   * Add `-Xbootclasspath/p:c:\path\to\java-time-backport-1.0.0.jar` to your JVM arguments
* You need to specify a "default" timezone
   * For me, it wasn't working with system default : "Europe/Paris"
   * it works if I specify `user.timezone=UTC`
      * for example, with `-Duser.timezone=UTC`
